export const SIGNUP_USER_START = 'SIGNUP_USER_START';
export const SIGNUP_USER_END = 'SIGNUP_USER_END';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const SIGNIN_USER_START = 'SIGNIN_USER_START';
export const SIGNIN_USER_END = 'SIGNIN_USER_END';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNIN_USER_FAILURE = 'SIGNIN_USER_FAILURE';
